---
###########################
# Setup Kubernetes Add-Ons
###########################

- hosts: localhost
  connection: local
  roles:
    - addons-dashboard
    - addons-heapster
    - addons-storage-class
    - addons-route53-mapper
