---

# Name of the Kubernetes cluster
# Will be used to name also other resources (IAM roles, instances, S3 buckets, etc.)
cluster_name: en341-k8s-qs

#####
# Mandatory AWS tags
#####

# Example:
# tags:
#   Creator: ab123
#   CostCenter: 123456
#   Product: MyProduct
#   Environment: DEV

tags:
  Creator: en341
  CostCenter: 665050
  Product: Risk
  Environment: DEV

#####
# Remote access and security
#####

# SSH key to access the cluster
ssh_public_key: ~/.ssh/id_rsa.pub
ssh_private_key: ~/.ssh/id_rsa

# CIDR from which is cluster access allowed
ssh_cidr: 0.0.0.0/0

# CIDR from which is Kubernetes API access allowed
api_cidr: 0.0.0.0/0

#####
# AWS setup details
#####
aws_region: eu-central-1
aws_zone: eu-central-1a
vpc_id: vpc-969d43fe
subnet_id: subnet-ca9dcca2

#####
# Kubernetes setup details
#####
ec2_instance_type: t2.medium
ec2_disk_size: 40
kubernetes_network: calico
kubernetes_node_count: 3

#####
# IAM Role configuration
#####

# DBG Role template URL
template_url: https://s3.eu-central-1.amazonaws.com/init-prod-dev-s3bucket-15205kjmp3ix0/RoleGeneration/DBG-CORE-ROLE-Trigger.template

# DBG IAM prefix
iam_prefix: DBG-DEV-
