---

####################
# Install Storage Class
####################

- name: Add Storage Class configuration
  template:
    src: storage-class.yaml.j2
    dest: /tmp/storage-class.yaml
    mode: 0644
  become: false

- name: Load storage class into configuration
  command: "kubectl --kubeconfig {{ kubeconfig_file }} create -f /tmp/storage-class.yaml"
